"""Stable version and error-code constants for MissionGraph contracts."""

from __future__ import annotations

AST_VERSION = "1.0"
TRACE_VERSION = "1.0"

ERROR_CODE_CONTRACT_INPUT_VIOLATION = "CONTRACT_INPUT_VIOLATION"
ERROR_CODE_CONTRACT_OUTPUT_VIOLATION = "CONTRACT_OUTPUT_VIOLATION"
ERROR_CODE_ARTIFACT_CONSUME_MISSING = "ARTIFACT_CONSUME_MISSING"
ERROR_CODE_ARTIFACT_OUTPUT_MISSING = "ARTIFACT_OUTPUT_MISSING"
ERROR_CODE_RUNTIME_EXECUTION_FAILURE = "RUNTIME_EXECUTION_FAILURE"
ERROR_CODE_WORKER_OUTPUT_JSON_INVALID = "WORKER_OUTPUT_JSON_INVALID"
ERROR_CODE_WORKER_EXIT_NONZERO = "WORKER_EXIT_NONZERO"
ERROR_CODE_WORKER_TIMEOUT = "WORKER_TIMEOUT"
